# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build main.go

    - name: Deploy to target
      run: |
        chmod +x main
  
        mkdir -p ~/.ssh
        ssh-keyscan target >> ~/.ssh/known_hosts

        echo "${{ secrets.TARGET_SSH_KEY }}" > ~/.ssh/mykey

        chmod 600 ~/.ssh/mykey

        export ssh_key="~/.ssh/mykey"
        export ssh_user="laborant"
        
        ssh -i ${ssh_key} laborant@target 'sudo systemctl stop main.service'
        
        scp -i ${ssh_key} main ${ssh_user}@target:
        
        scp -i ${ssh_key} main.service ${ssh_user}@target:
        
        ssh -i ${ssh_key} laborant@target 'sudo mv /home/laborant/main.service /etc/systemd/system/main.service'
        
        ssh -i ${ssh_key} laborant@target 'sudo mv /home/laborant/main /opt/main'
        
        ssh -i ${ssh_key} laborant@target 'sudo systemctl daemon-reload'
        
        ssh -i ${ssh_key} laborant@target 'sudo systemctl enable --now main.service'


